apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scaleupjob
  namespace: testspace
spec:
  schedule: "50 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scale-user
          containers:
          - name: scaleupjob
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - kubectl patch hpa testspace-podinfo-test --namespace=testspace --patch '{"spec":{"minReplicas":1}}'
          restartPolicy: OnFailure