apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scaledownjob
  namespace: testspace
spec:
  schedule: "14 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scale-user
          containers:
          - name: scaledownjob
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - kubectl patch hpa testspace-podinfo-test --namespace=testspace --patch '{"spec":{"minReplicas":1}}'
          restartPolicy: OnFailure