apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: service-scale-up-job
  namespace: testspace
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testscaleup
            image: scaleup
            args:
              - "kubectl patch hpa testspace-podinfo-test --patch '{\"spec\":{\"minReplicas\":5}}'"
