apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: testService
  namespace: testspace
spec:
  releaseName: test
  targetNamespace: testspace
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: git@github.com:OliverK99/helmtest
    ref: master
    path: charts