apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: serviceacc
  namespace: testspace
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: serviceacc
  chart:
    git: git@github.com:OliverK99/helmtest
    path: charts/chart1
    ref: master