apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.helmServiceAccount.name }}
  namespace: {{ .Release.namespace }}
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "somesecretgoeshere"
    }