apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scaleupjob1
  namespace: testspace
spec:
  schedule: "10 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scale-user
          containers:
          - name: scaleupjob
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - kubectl patch hpa testspace-podinfo-test --namespace=testspace --patch '{"spec":{"minReplicas":5}}'
            resources:
              requests:
                cpu: "100m"
                memory: "200Mi"
              limits:
                cpu: "100m"
                memory: "200Mi" 
          restartPolicy: OnFailure