apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scaledownjob
  namespace: testspace
spec:
  schedule: "14 15 * * *" # timezone: UTC -> -1h
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scale-user
          containers:
          - name: scaledownjob #use name for container
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - kubectl patch hpa testspace-podinfo-test --namespace=testspace --patch '{"spec":{"minReplicas":1}}' 
            resources:
              requests:
                cpu: "100m"
                memory: "200Mi"
              limits:
                cpu: "100m"
                memory: "200Mi" 
          restartPolicy: OnFailure