apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scale-rolebinding
  namespace: testspace
roleRef:
  kind: Role
  name: scale-role
  namespace: testspace
subjects:
- kind: ServiceAccount
  name: scale-user
  namespace: testspace